language: python

python:
  - '3.5'
  - '3.6'

install:
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  
env:
- LANG=en_US.UTF-8
- LC_ALL=en_US.UTF-8

script:
  - nosetests
